### ISSUE TITLE
Recaptcha is not showing

### ISSUE THREAD

**Issue by mikahanninen** [getgrav/grav-plugin-guestbook#14]
My site: http://uwc11.beissi.net/guestbook

I have entered guestbook.md by copy pasting example content on the plugin page and just changed the keys. In addition to this I have added JS file told my Google Recaptcha site into base.html.twig.

Browser console shows error `recaptcha__fi.js:292 Uncaught Error: Missing required parameters: sitekey`

If I manually add `<div class="g-recaptcha" data-sitekey="INSERT_KEY_HERE"></div>` then the RECAPTCHA shows but ofc not in the place it should appear.

Guestbook plugin v0.5.0
Form plugin v2.3.1
Grav v1.2.2
Admin v1.3.3

**Comment by mikahanninen** [comment]
I have added screenshot below because I am disabling guestbook on my site for now..

<img width="1139" alt="guestbook___unofficial_world_cup" src="https://cloud.githubusercontent.com/assets/1019528/25086480/99d01ac2-2370-11e7-9a1a-24c0f149b4c6.png">

**Comment by mikahanninen** [comment]
couple things in the **grav.log**

`[2017-04-17 01:12:38] grav.CRITICAL: A template that extends another one cannot include contents outside Twig blocks. Did you forget to put the contents inside a {% block %} tag? - Trace: #0 /var/www/html/uwc11/vendor/twig/twig/lib/Twig/Parser.php(399): Twig_Parser->filterBodyNodes(Object(Twig_Node_Include)) #1 /var/www/html/uwc11/vendor/twig/twig/lib/Twig/Parser.php(105): Twig_Parser->filterBodyNodes(Object(Twig_Node)) #2 /var/www/html/uwc11/vendor/twig/twig/lib/Twig/Environment.php(692): Twig_Parser->parse(Object(Twig_TokenStream)) #3 /var/www/html/uwc11/vendor/twig/twig/lib/Twig/Environment.php(750): Twig_Environment->parse(Object(Twig_TokenStream)) #4 /var/www/html/uwc11/vendor/twig/twig/lib/Twig/Environment.php(447): Twig_Environment->compileSource(Object(Twig_Source)) #5 /var/www/html/uwc11/vendor/twig/twig/lib/Twig/Environment.php(362): Twig_Environment->loadTemplate('default.html.tw...') #6 /var/www/html/uwc11/system/src/Grav/Common/Twig/Twig.php(346): Twig_Environment->render('default.html.tw...', Array) #7 /var/www/html/uwc11/system/src/Grav/Common/Service/OutputServiceProvider.php(19): Grav\Common\Twig\Twig->processSite('html') #8 /var/www/html/uwc11/vendor/pimple/pimple/src/Pimple/Container.php(113): Grav\Common\Service\OutputServiceProvider->Grav\Common\Service\{closure}(Object(Grav\Common\Grav)) #9 /var/www/html/uwc11/system/src/Grav/Common/Processors/RenderProcessor.php(18): Pimple\Container->offsetGet('output') #10 /var/www/html/uwc11/system/src/Grav/Common/Grav.php(126): Grav\Common\Processors\RenderProcessor->process() #11 /var/www/html/uwc11/system/src/Grav/Common/Grav.php(368): Grav\Common\Grav->Grav\Common\{closure}() #12 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('render', 'Render', Object(Closure)) #13 /var/www/html/uwc11/system/src/Grav/Common/Grav.php(344): call_user_func_array(Object(Closure), Array) #14 /var/www/html/uwc11/system/src/Grav/Common/Grav.php(127): Grav\Common\Grav->__call('measureTime', Array) #15 /var/www/html/uwc11/system/src/Grav/Common/Grav.php(127): Grav\Common\Grav->measureTime('render', 'Render', Object(Closure)) #16 /var/www/html/uwc11/index.php(52): Grav\Common\Grav->process() #17 {main} [] []

[2017-04-17 12:54:30] grav.CRITICAL: Template "guestbook.html.twig" is not defined. - Trace: #0 /var/www/html/uwc11/system/src/Grav/Common/Service/OutputServiceProvider.php(19): Grav\Common\Twig\Twig->processSite('html') #1 /var/www/html/uwc11/vendor/pimple/pimple/src/Pimple/Container.php(113): Grav\Common\Service\OutputServiceProvider->Grav\Common\Service\{closure}(Object(Grav\Common\Grav)) #2 /var/www/html/uwc11/system/src/Grav/Common/Processors/RenderProcessor.php(18): Pimple\Container->offsetGet('output') #3 /var/www/html/uwc11/system/src/Grav/Common/Grav.php(126): Grav\Common\Processors\RenderProcessor->process() #4 /var/www/html/uwc11/system/src/Grav/Common/Grav.php(368): Grav\Common\Grav->Grav\Common\{closure}() #5 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('render', 'Render', Object(Closure)) #6 /var/www/html/uwc11/system/src/Grav/Common/Grav.php(344): call_user_func_array(Object(Closure), Array) #7 /var/www/html/uwc11/system/src/Grav/Common/Grav.php(127): Grav\Common\Grav->__call('measureTime', Array) #8 /var/www/html/uwc11/system/src/Grav/Common/Grav.php(127): Grav\Common\Grav->measureTime('render', 'Render', Object(Closure)) #9 /var/www/html/uwc11/index.php(52): Grav\Common\Grav->process() #10 {main} [] []`

**Comment by flaviocopes** [comment]
There was this typo in the README: https://github.com/getgrav/grav-plugin-guestbook/commit/18861bef320a34c52928dc5fac427ff81536938e 

The captcha used to work even with the typo, but maybe something changed in the latest releases.

**Comment by mikahanninen** [comment]
I got this plugin working so this issue can be closed. I had to configure email stuff which was told in detail in the plugin page.

**Comment by Akhidenor12345** [comment]
I never thought i could smile and be in a happy marriage again if not for the help of DR Moses . I got the doctors Email and i emailed him, he got back to me with some encouraging words, he got me some herbs cream which i use for just 8 days and i began to feel the male enhancement , and without surgery. This went on for a little period of about 10 days and to my surprise my wife keeps screaming that she love my big dick now. Now my wife no longer cheat on me, and my male enhancement  is now about 10.5 inches long on erection and off course very large round. And now my wife uses breasts, hips and bums enlargement. I and my wife are very happy for the help rendered to me by DR Moses HERBS, and i want to say a big thanks to Doctor for the help. you can  call/whats-app him directly on +2349060529305
website:https://bubaherbalmiraclem.wixsite.com/website
Facebook page ;https://www.facebook.com/profile.php?id=61559577240930


DOCTOR Moses Buba CAN AS WELL HELP THE FOLLOWING PROBLEMS
1. HIV/AIDS SPELL
2. HERPES SPELL
3. CANCER SPELL
4 IF YOU WANT YOUR EX LOVER BACK SPELL
5 IF YOU NEED A BABY SPELLhim to solve
6 LOW SPERM COUNT SPELL
get all your problem solve. No problem is too big for him to solve.
