### ISSUE TITLE
Bug with the template

### ISSUE THREAD

**Issue by ghost** [getgrav/grav-plugin-guestbook#2]
I create a guestbook page with admin plugin

File create : guestbook.fr.md

And on front 

RuntimeException (400)
Template "guestbook.html.twig" is not defined.

Thanks

**Comment by flaviocopes** [comment]
Right, fixed by https://github.com/getgrav/grav-plugin-guestbook/commit/ca79a00b3c30de6f1afca9be6eb8ba56b5daf487. 
Currently you need to copy the guestbook twig template to the theme templates, will publish a release soon.
