### ISSUE TITLE
Posting entries to the page forntmatter instead of the data folder

### ISSUE THREAD

**Issue by mikegcox** [getgrav/grav-plugin-guestbook#6]
Would it be possible to post guestbook entires to the page front-matter instead of the data folder?  I  realize this would require a re-write to some extent but wondering your thoughts on doing it this way.  Right now, the guestbook is really nice, it works great but there is no way to edit entries from the Admin module.  If the guestbook form posted entries directly into the page front-matter, we could edit the entries from the "Pages" admin.  I was looking at the code in `guestbook.php`, but I am not sharp enough to figure it out.

**Comment by w00fz** [comment]
I think this could be a good candidate for the data plugin. I believe we discussed this at some point but not quite sure where we stand with it now.

/cc @flaviocopes, @rhukster

**Comment by mikegcox** [comment]
I can get the guestbook to load in the data plugin, but you cannot edit the entries as far as I know.  Really, all I would need is the ability to delete guestbook entries.  Being able to moderate the guestbook would be even better, so that unwanted entries would never appear.

**Comment by w00fz** [comment]
Yes I know you can't edit, that's where I think expanding the behavior on the data plugin would make sense. A way to manage data in a CRUD way, right now the data plugin mostly serves as a viewer which can be useful for things like logs,  however I can see CRUD being beneficial here.

**Comment by rhukster** [comment]
Mike it's possible to add CRUD operations to guestbook in the admin even with the data stored in user/data. Just need to be added :)

**Comment by mikegcox** [comment]
Thanks Andy,  I figured that to be the case and I know these modules are done voluntarily so features come as time permits.  I appreciate the effort.  I just think it could be an easy way to get CRUD operations to this plugin.  I am not at all a good code person so I was curious if it would be possible to have the form post to the page front-matter instead of the Data folder?
